name: Scalafmt

permissions: {}

on:
  pull_request:
    branches: ['**']

jobs:
  build:
    name: Code is formatted
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Check project is formatted
        uses: jrouly/scalafmt-native-action@v4
        with:
          arguments: '--list --mode diff-ref=origin/main'
